import { Button, Palette } from "std-widgets.slint";

export component MainWindow inherits Window {
    in-out property <string> hotkeys;
    in-out property <string> current-pressed-keys;

    callback save-hotkeys(string);

    title: "快捷键设置";
    width: 350px;
    height: 200px;
    icon: @image-url("../src/assets/hsarec.png");

    forward-focus: key-handler;
    key-handler := FocusScope {
        key-pressed(event) => {
            debug("Key pressed: ", event.text, " with modifiers: ", event.modifiers);
            if (event.text == Key.Escape) {
                root.current-pressed-keys = "";
                return accept;
            }

            if (event.text == Key.Control || event.text == Key.Shift || event.text == Key.Alt || event.text == Key.Meta) {
                // Do nothing when only a modifier is pressed.
                return accept;
            }

            // For all other keys, construct the string.
            // This might result in an incomplete string like "ctrl+alt+" if the
            // OS / windowing system reports an empty text for that combination (e.g. AltGr).
            root.current-pressed-keys = (event.modifiers.control ? "ctrl+" : "")
                                      + (event.modifiers.alt ? "alt+" : "")
                                      + (event.modifiers.shift ? "shift+" : "")
                                      + (event.modifiers.meta ? "meta+" : "")
                                      + event.text;
            accept
        }
    }

    VerticalLayout {
        padding: 15px;
        spacing: 15px;

        Text {
            text: "快捷键设置";
            horizontal-alignment: center;
            font-size: 20px;
            font-weight: 700;
        }

        GridLayout {
            spacing: 10px;
            Row {
                Text { text: "当前快捷键:"; vertical-alignment: center; }
                Text { text: root.hotkeys; vertical-alignment: center; }
            }
            Row {
                Text { text: "当前按下的键:"; vertical-alignment: center; }
                Text { text: root.current-pressed-keys == "" ? "无" : root.current-pressed-keys; vertical-alignment: center; }
            }
        }

        Button {
            text: "保存快捷键";
            enabled: root.current-pressed-keys != "";
            clicked => {
                root.save-hotkeys(root.current-pressed-keys);
            }
        }
    }
}